apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
  namespace: app-demo
data:
  01_init.sql: |
    CREATE DATABASE IF NOT EXISTS `loja`;

    -- app user para qualquer origem e para localhost
    CREATE USER IF NOT EXISTS 'pedro'@'%' IDENTIFIED WITH mysql_native_password BY '123456';
    CREATE USER IF NOT EXISTS 'pedro'@'localhost' IDENTIFIED WITH mysql_native_password BY '123456';

    ALTER USER 'pedro'@'%' IDENTIFIED WITH mysql_native_password BY '123456';
    ALTER USER 'pedro'@'localhost' IDENTIFIED WITH mysql_native_password BY '123456';

    GRANT ALL PRIVILEGES ON `loja`.* TO 'pedro'@'%';
    GRANT ALL PRIVILEGES ON `loja`.* TO 'pedro'@'localhost';