
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: app-demo
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
