
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: app-demo
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30020
