
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app-demo
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
